name: Build and Test

on:
  schedule:
    # Weekday (22=10pm UTC). Evaluates to 8am AEST.
    - cron: '0 22 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
      - convivial-recommended-[0-9]+
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' || !github.event.pull_request.draft }}
    name: Build Convivial Recommended
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/morpht/ci-php:8.2.14-memory
      env:
        PHP_MEMORY_LIMIT: 512M

    steps:
      - name: Checkout.
        uses: actions/checkout@v3
      - name: Execute Composer install
        run: composer install
      - name: Validate composer.json and composer.lock
        run: composer validate
