# Triggers the nightly workflow.
on:
  schedule:
    # Weekday (22=10pm UTC). Evaluates to 8am AEST.
    - cron: '0 22 * * *'

jobs:
  build:
    name: Build Convivial Recommended
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout.
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Validate composer.json
        run: composer validate
      - name: Setup PHP and tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          extensions: mbstring, gd, intl, yaml, bcmath, curl
      - name: Execute Composer install
        run: composer install
